version: "3"

services:
  denb_boot-web01: 
    container_name: denb_boot
    hostname: denb_boot
    ports:
      - "9003:8080"
    build:
      context: ./
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - web
networks: # 가장 기본적인 bridge 네트워크.
  web:
    driver: bridge
