version: "3"

services:
  web:
    container_name: denb_boot
    hostname: denb_boot
    ports:
      - "9904:8080"
    build:
      context: ./
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - web


networks: # 가장 기본적인 bridge 네트워크.
  web:
    driver: bridge
